apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:7.4-fpm
        ports:
        - containerPort: 9000 
      - name: php-exporter
        image: hipages/php-fpm_exporter:latest # Exportador de métricas para PHP-FPM
        args:
        - "--phpfpm.scrape-uri=tcp://127.0.0.1:9000/status" # URI de PHP-FPM
        ports:
        - containerPort: 9253 # Puerto que expondrá las métricas
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9253" # Puerto del exportador de métricas
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: php-fpm
  - port: 9253
    targetPort: 9253
    name: metrics
  selector:
    app: php
