apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "mysql-service"  # Nombre del servicio MySQL en tu clúster
        - name: PMA_PORT
          value: "3306"  # Puerto en el que MySQL escucha
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32324  # Puedes cambiar este puerto si lo necesitas
  selector:
    app: phpmyadmin