apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "mysql-service"  # Nombre del servicio MySQL en tu clúster
        - name: PMA_PORT
          value: "3306"  # Puerto en el que MySQL escucha
        ports:
        - containerPort: 80
        volumeMounts:
        - name: session
          mountPath: /sessions
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        args:
        - -nginx.scrape-uri=http://localhost:80/nginx_status
        ports:
        - containerPort: 9113 # Puerto para métricas de nginx-exporter
      volumes:
      - name: session
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113" # Puerto del exportador para métricas
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32324
    name: http
  - port: 9113
    targetPort: 9113
    name: metrics
  selector:
    app: phpmyadmin
