apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      - name: mysqld-exporter
        image: prom/mysqld-exporter:v0.14.0
        env:
        - name: DATA_SOURCE_NAME
          value: "root:$(MYSQL_ROOT_PASSWORD)@(127.0.0.1:3306)/"
        ports:
        - containerPort: 9104 # Puerto de métricas de mysqld-exporter
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104" # Puerto del exportador de métricas
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  - port: 9104
    targetPort: 9104
    name: metrics
  selector:
    app: mysql
