apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "mysql-service"  # Nombre del servicio MySQL en tu clúster
        - name: PMA_PORT
          value: "3306"  # Puerto en el que MySQL escucha
        ports:
        - containerPort: 80
        volumeMounts:
        - name: session
          mountPath: /sessions
      volumes:
      - name: session
        emptyDir: {}
