apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: sufimago/flask-app:latest  # La imagen que has creado para la app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: "mysql-service"  # Referencia al servicio de MySQL
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "pro-pass"  # La contraseña de root
            - name: MYSQL_DB
              value: "pro.db"
            - name: REDIS_HOST
              value: "redis-service"  # Referencia al servicio de Redis
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    prometheus.io/scrape: "true"          # Habilitar scraping de métricas para Prometheus
    prometheus.io/port: "5000"           # Puerto donde expone métricas Flask
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: flask
