apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default  # O el namespace que estés usando
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;
            server_name localhost;

            root /usr/share/nginx/html;
            index index.php index.html;

            location ~ \.php$ {
                fastcgi_pass php-service:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }

            location / {
                try_files $uri $uri/ =404;
            }
        }
    }
