apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
        
      - job_name: "flask"
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: flask-service  

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod

      - job_name: 'prometheus'
        static_configs:
        - targets:
          - localhost:9090
