apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cGFzc3dvcmQ= # 'password' en base64
  username: cm9vdA== # 'root' en base64
  password: cHJvLXBhc3M= # 'pro-pass' en base64
