apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <html>
      <head><title>Mi Web</title></head>
      <body><h1>¡Hola Mundo desde Nginx!</h1></body>
    </html>
