name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run black (code formatter)
        run: black .

      - name: Run flake8 (code linter)
        run: flake8 --ignore=E501,F841,W503 .

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    name: Deployment Instructions
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deployment instructions
        run: |
          echo "To deploy locally, run the following commands:"
          echo "docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest"
          echo "docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/flask-app:latest"
